test Find home domain

diff --git a/.github/workflows/basic_tests.yml b/.github/workflows/basic_tests.yml
--- a/.github/workflows/basic_tests.yml
+++ b/.github/workflows/basic_tests.yml
@@ -8,38 +8,38 @@ on:
   workflow_call: # Allows this workflow to be called from another workflow
 
 jobs:
-  build_and_test:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
-    - name: Set up JDK 11
-      uses: actions/setup-java@v2
-      with:
-        java-version: '11'
-        distribution: 'adopt'
-
-    - name: Check code formatting
-      run: ./gradlew spotlessCheck || echo "❌ Your code is not properly formatted. You can run './gradlew spotlessApply' to format it. 👀"
-
-    - name: Clean, Build and Test
-      run: ./gradlew clean build
-
-    - name: Print Test Results
-      if: success() || failure()
-      run: |
-        echo "\n\n*** API Schema test report ***\n"
-        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/api-schema/build/reports/tests/test/index.html
-        echo "\n\n*** SEP test report ***\n"
-        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/core/build/reports/tests/test/index.html
-        echo "\n\n*** Platform test report ***\n"
-        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/platform/build/reports/tests/test/index.html
-        echo "\n\n*** Integration tests report ***\n"
-        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/integration-tests/build/reports/tests/test/index.html
-        echo "\n\n*** Anchor reference server test report ***\n"
-        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/anchor-reference-server/build/reports/tests/test/index.html
+#  build_and_test:
+#    runs-on: ubuntu-latest
+#    steps:
+#    - uses: actions/checkout@v3
+#    - name: Set up JDK 11
+#      uses: actions/setup-java@v2
+#      with:
+#        java-version: '11'
+#        distribution: 'adopt'
+#
+#    - name: Check code formatting
+#      run: ./gradlew spotlessCheck || echo "❌ Your code is not properly formatted. You can run './gradlew spotlessApply' to format it. 👀"
+#
+#    - name: Clean, Build and Test
+#      run: ./gradlew clean build
+#
+#    - name: Print Test Results
+#      if: success() || failure()
+#      run: |
+#        echo "\n\n*** API Schema test report ***\n"
+#        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/api-schema/build/reports/tests/test/index.html
+#        echo "\n\n*** SEP test report ***\n"
+#        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/core/build/reports/tests/test/index.html
+#        echo "\n\n*** Platform test report ***\n"
+#        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/platform/build/reports/tests/test/index.html
+#        echo "\n\n*** Integration tests report ***\n"
+#        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/integration-tests/build/reports/tests/test/index.html
+#        echo "\n\n*** Anchor reference server test report ***\n"
+#        cat /home/runner/work/java-stellar-anchor-sdk/java-stellar-anchor-sdk/anchor-reference-server/build/reports/tests/test/index.html
 
   sep_validation_suite:
-    needs: [build_and_test]
+#    needs: [build_and_test]
     runs-on: ubuntu-latest
     name: Validate SEPs (1, 10, 12, 31, 38)
     env:
@@ -51,6 +51,8 @@ jobs:
       - name: Find Home Domain (Preview or Dev)
         id: endpoint-finder
         run: |
+          echo ${{github.event.pull_request.number}}
+          echo $PR_NUMBER
           export HOME_DOMAIN=https://anchor-sep-server-dev.stellar.org
           if [ ! -z "$PR_NUMBER" ]
           then
@@ -59,21 +61,22 @@ jobs:
           echo HOME_DOMAIN=$HOME_DOMAIN
           echo "::set-output name=HOME_DOMAIN::$HOME_DOMAIN"
 
-      - name: Install Node
-        uses: actions/setup-node@v2
-        with:
-          node-version: 14
-
-      - name: Run Validation Tool
-        env:
-          HOME_DOMAIN: ${{ steps.endpoint-finder.outputs.HOME_DOMAIN }}
-        run: |
-          npm install -g @stellar/anchor-tests
-          stellar-anchor-tests --home-domain $HOME_DOMAIN --seps 1 10 12 31 38 --sep-config platform/src/test/resources/stellar-anchor-tests-sep-config.json
+#      - name: Install Node
+#        uses: actions/setup-node@v2
+#        with:
+#          node-version: 14
+#
+#      - name: Run Validation Tool
+#        env:
+#          HOME_DOMAIN: ${{ steps.endpoint-finder.outputs.HOME_DOMAIN }}
+#        run: |
+#          npm install -g @stellar/anchor-tests
+#          stellar-anchor-tests --home-domain $HOME_DOMAIN --seps 1 10 12 31 38 --sep-config platform/src/test/resources/stellar-anchor-tests-sep-config.json
 
   complete:
     if: always()
-    needs: [build_and_test, sep_validation_suite]
+#    needs: [build_and_test, sep_validation_suite]
+    needs: [sep_validation_suite]
     runs-on: ubuntu-latest
     steps:
     - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
