Fix release tag

diff --git a/.github/workflows/wf_release_created_or_updated.yml b/.github/workflows/wf_release_created_or_updated.yml
--- a/.github/workflows/wf_release_created_or_updated.yml
+++ b/.github/workflows/wf_release_created_or_updated.yml
@@ -18,39 +18,31 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Get anchor platform project version
+      - name: Get EXPECTED_RELEASE_TAG
         shell: bash
-        id: get_version
-        run: echo ::set-output name=VERSION::$(${{github.workspace}}/gradlew -q printVersionName)
-
-      - name: Echo versions
-        run: echo "Release version=${{ github.event.release.tag_name }}, Project version=${{ steps.get_version.outputs.VERSION }}"
+        run: |
+          echo "EXPECTED_RELEASE_TAG=release-$(${{github.workspace}}/gradlew -q printVersionName)"
+          echo "EXPECTED_RELEASE_TAG=release-$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV
 
       - name: Fail if the release version and the project version do not match
-        if: ${{ '${{ github.event.release.tag_name }}' != 'release-${{ steps.get_version.outputs.VERSION }}' }}
-        run: exit 1
+        if: ${{ github.event.release.tag_name != env.EXPECTED_RELEASE_TAG }}
+        run: |
+          echo "The release tag is invalid: [${{ github.event.release.tag_name }}]"
+          echo "The expected release tag is: [${{ env.EXPECTED_RELEASE_TAG }}]"         
+          echo "The release tag must match project version with [release-] prefix."
+          exit 1
 
-      - name: Get current date
-        id: get_date
-        run: echo "::set-output name=DATE::$(date +'%Y-%m-%d')"
-
-      - name: Calculate Github SHA
-        shell: bash
-        id: get_sha
-        run: echo ::set-output name=SHA::$(git rev-parse --short ${{ github.sha }} )
-
-      - name: Login to DockerHub
-        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
+      - name: Docker Login
+        uses: docker/login-action@v2.1.0
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push to DockerHub
-        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
+      - name: Build and push Docker images
+        uses: docker/build-push-action@v4.0.0
         with:
           push: true
-          #          tags: stellar/anchor-platform:${{ github.event.release.tag_name }}-rc,stellar/anchor-platform:latest
-          tags: stellar/anchor-platform:test-rc
+          tags: stellar/anchor-platform:${{ env.EXPECTED_RELEASE_TAG }},stellar/anchor-platform:latest
           file: Dockerfile
 
   complete:
